### PR TITLE
Adds comments model

### PR DESCRIPTION
**Pull request by cindywu**

### CODE REVIEW

**Comment by dennyluan** [comment]
Note for later, remove the scaffolds style file.

**Comment by dennyluan** [comment]
I think once we implement RT-collab, doing an idempotent update for the collection of comments might be preferable:

```ruby
# idempotent approach
parsed_params = JSON.parse(params["plugins"])
if comments_data = parsed_params["comments"]

  comments = []
  comments_data.each do |comment_data|
    comment = Comment.find_or_create_by(
      data_key: comment_data["id"].to_s,
      post_id: @post.id)

    comment.update_attributes(
      comment: comment_data["text"],
      data_from: comment_data["from"],
      data_to: comment_data["to"]
    )
    comments << comment
  end
  comments_to_delete = @post.comments - comments
  comments_to_delete.each do |comment|
    comment.destroy
  end
end
```

**Comment by dennyluan** [comment]
This PR pulls out commenting from the `plugins` on `Post` and into a new `Comment` model to save for every new editor annotation.

**Comment by cindywu** [comment]
👍🏽

**Pull request merged**
