### PR TITLE
Update license to MIT/Apache-2

### PR DESCRIPTION
**Pull request by cindywu**
- [x] adds dual mit/apache-2 license
- [x] all contributions (unless explicitly stated otherwise) will be under the apache-2 license

will discuss at our tuesday 12/17 meeting before it is ready for review

### CODE REVIEW

**Comment by cindywu** [comment]
today @dennyluan @alexkrolick and i decided to open this up for discussion.

>Today I am recommending we adopt an MIT/Apache-2 dual license.

our notion is not public, but this identical copy is https://cindywu.org/@cindy/licensing-our-open-source-software-cxE1gN

i am open to hearing the concerns of a dual apache-2/MIT license. questions regarding specific business scenarios for jelly can also be asked here.

discuss!

**Comment by breck7** [comment]
I think MIT is solid.

I don't think you can go wrong with that.

On the public domain side I think great projects are SQLite (https://www.sqlite.org/index.html) and the WWW. Actually a better approach may just be to search Github.

Here are the 125k+ projects that use the unlicense: https://github.com/search?utf8=%E2%9C%93&q=license%3Aunlicense&type=Repositories&ref=advsearch&l=&l=

And the 4M+ that use MIT: https://github.com/search?q=license%3Amit&type=Repositories

**Comment by cindywu** [comment]
@dennyluan can you state your opinion here before tuesday 1/7?

**Comment by dennyluan** [comment]
I'm down with moving forward on this. My rationale for this decision is that it keeps with the spirit of the project to be free and open, and let's see what happens!

**Pull request merged**
